# Generated by Django 5.2.7 on 2025-10-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loop_app', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
