# Generated by Django 5.2.7 on 2025-10-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loop_app', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
